### ISSUE TITLE
[SCRATCH PAD] Uncaptured tasks for future milestones

### ISSUE THREAD

**Issue by hartste90** [hartste90/ticket-tracker#4]
- [ ] Donation footer at bottom and link to Venmo/payout platform
- [ ] Mobile responsiveness
- [ ] Don't show listings after they have happened
- [ ] Delete listings 2 months after they have completed?
- [ ] FAQ link on password page and more information about what the site is for
- [ ] Ability to report a post (short blurb why, alerts me somehow to my email (ability to turn off / ignore this)
- [ ] Filter listings by name (search bar)
